version: '2.1'

volumes:
  blockscoutpostgres:

networks:
  bharatblockchain:
    name: bharatblockchain
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24

services:
  generator:
    build:
      context: generator/.
    environment:
      - WRITERS=1
    volumes:
      - ./volumes/writers:/writers
    networks:
      bharatblockchain:
        ipv4_address: 172.16.239.34

  mainnet-node1:
    user: root
    container_name: bbnmainnet-node-1
    volumes: 
      - ./config:/opt/besu/config
      - ./volumes/writers/1/keys:/opt/besu/besu/keys/

    image: hyperledger/besu:23.10.2
    command: 
      --config-file=/opt/besu/config/besu/config.toml
      --genesis-file=/opt/besu/config/besu/genesis.json
      --static-nodes-file=/opt/besu/config/besu/static-nodes.json
      --node-private-key-file=/opt/besu/besu/keys/key
      # "--rpc-http-api=WEB3,ETH,NET,IBFT,ADMIN",
      # "--rpc-ws-api='WEB3,ETH,NET,IBFT,ADMIN'"
    ports:
      - "8545:8545"
      - "8546:8549"
      - "9545:9545"
    networks:
      bharatblockchain:
        ipv4_address: 172.16.239.35
    restart: always
